import type {
  PostgresTopic,
  ConnectionDriver,
  PgExample,
  EnterpriseUseCase,
} from '@/types/postgresql';

export const postgresTopics: PostgresTopic[] = [
  {
    slug: 'prerequisites-setup',
    title: 'Prerequisites & Setup',
    shortTitle: 'Setup',
    description: 'Installation, tools (psql, pgAdmin, DBeaver), and pg_hba.conf configuration.',
    icon: 'setup',
    order: 1,
  },
  {
    slug: 'why-postgresql',
    title: 'Why PostgreSQL?',
    shortTitle: 'Why PG',
    description: 'Capabilities, enterprise use cases, cost efficiency, and migration reasons.',
    icon: 'why',
    order: 2,
  },
  {
    slug: 'backend-connections',
    title: 'Backend Connections',
    shortTitle: 'Connections',
    description: 'How PostgreSQL connects to Node.js, Python, Java, and C++ with animated flow diagrams.',
    icon: 'connections',
    order: 3,
  },
  {
    slug: 'practice-examples',
    title: 'Practice Examples',
    shortTitle: 'Practice',
    description: 'Pre-defined SQL exercises from basic to intermediate with hints and solutions.',
    icon: 'practice',
    order: 4,
  },
  {
    slug: 'official-docs-summary',
    title: 'Official Docs Summary',
    shortTitle: 'Docs Summary',
    description: 'Condensed PostgreSQL official docs: data types, config, backup, and replication.',
    icon: 'docs',
    order: 5,
  },
];

export const connectionDrivers: ConnectionDriver[] = [
  {
    language: 'nodejs',
    languageLabel: 'Node.js',
    methods: [
      {
        id: 'raw-driver',
        label: 'pg (raw driver)',
        library: 'pg',
        description: 'Low-level PostgreSQL client for Node.js with full protocol support.',
        steps: [
          'Import pg Client',
          'Create connection config (host, port, database, user, password)',
          'Connect to database',
          'Execute query',
          'Process results',
          'Release connection',
        ],
        codeSnippet: [
          "const { Client } = require('pg');",
          'const client = new Client({',
          "  host: 'localhost',",
          '  port: 5432,',
          "  database: 'mydb',",
          "  user: 'postgres',",
          "  password: 'secret',",
          '});',
          '',
          'await client.connect();',
          "const res = await client.query('SELECT NOW()');",
          'console.log(res.rows[0]);',
          'await client.end();',
        ].join('\n'),
      },
      {
        id: 'pool',
        label: 'pg Pool',
        library: 'pg',
        description: 'Connection pooling built into the pg library for production workloads.',
        steps: [
          'Import pg Pool',
          'Configure pool (max, idleTimeoutMillis, connectionTimeoutMillis)',
          'Acquire connection from pool',
          'Execute query',
          'Release connection back to pool',
          'Pool manages lifecycle automatically',
        ],
        codeSnippet: [
          "const { Pool } = require('pg');",
          'const pool = new Pool({',
          "  host: 'localhost',",
          '  port: 5432,',
          "  database: 'mydb',",
          "  user: 'postgres',",
          "  password: 'secret',",
          '  max: 20,',
          '  idleTimeoutMillis: 30000,',
          '});',
          '',
          "const res = await pool.query('SELECT * FROM users WHERE id = $1', [1]);",
          'console.log(res.rows[0]);',
        ].join('\n'),
      },
      {
        id: 'orm',
        label: 'Prisma ORM',
        library: 'prisma',
        description: 'Type-safe ORM with auto-generated queries, migrations, and schema management.',
        steps: [
          'Define schema in schema.prisma',
          'Run prisma generate to create client',
          'Import PrismaClient',
          'Execute type-safe queries',
          'Prisma handles connection pooling internally',
          'Disconnect on shutdown',
        ],
        codeSnippet: [
          "import { PrismaClient } from '@prisma/client';",
          'const prisma = new PrismaClient();',
          '',
          'const users = await prisma.user.findMany({',
          '  where: { active: true },',
          '  include: { posts: true },',
          '});',
          '',
          'await prisma.$disconnect();',
        ].join('\n'),
      },
    ],
  },
  {
    language: 'python',
    languageLabel: 'Python',
    methods: [
      {
        id: 'raw-driver',
        label: 'psycopg2',
        library: 'psycopg2',
        description: 'The most popular PostgreSQL adapter for Python, wrapping libpq.',
        steps: [
          'Import psycopg2',
          'Create connection with connect()',
          'Create cursor',
          'Execute query',
          'Fetch results',
          'Close cursor and connection',
        ],
        codeSnippet: [
          'import psycopg2',
          '',
          'conn = psycopg2.connect(',
          '    host="localhost",',
          '    port=5432,',
          '    dbname="mydb",',
          '    user="postgres",',
          '    password="secret"',
          ')',
          '',
          'cur = conn.cursor()',
          'cur.execute("SELECT NOW()")',
          'print(cur.fetchone())',
          'cur.close()',
          'conn.close()',
        ].join('\n'),
      },
      {
        id: 'pool',
        label: 'psycopg2 Pool',
        library: 'psycopg2',
        description: 'Thread-safe connection pooling for multi-threaded Python applications.',
        steps: [
          'Import ThreadedConnectionPool',
          'Create pool with min/max connections',
          'Get connection from pool',
          'Execute query',
          'Put connection back into pool',
          'Close all connections on shutdown',
        ],
        codeSnippet: [
          'from psycopg2 import pool',
          '',
          'conn_pool = pool.ThreadedConnectionPool(',
          '    minconn=2,',
          '    maxconn=10,',
          '    host="localhost",',
          '    dbname="mydb",',
          '    user="postgres",',
          '    password="secret"',
          ')',
          '',
          'conn = conn_pool.getconn()',
          'cur = conn.cursor()',
          'cur.execute("SELECT * FROM users WHERE id = %s", (1,))',
          'print(cur.fetchone())',
          'conn_pool.putconn(conn)',
        ].join('\n'),
      },
      {
        id: 'orm',
        label: 'SQLAlchemy',
        library: 'sqlalchemy',
        description: 'Full-featured Python ORM with both Core (SQL expression) and ORM patterns.',
        steps: [
          'Create engine with connection URL',
          'Define models with declarative base',
          'Create session',
          'Execute ORM queries',
          'Commit/rollback transactions',
          'Engine manages pool automatically',
        ],
        codeSnippet: [
          'from sqlalchemy import create_engine',
          'from sqlalchemy.orm import Session',
          '',
          'engine = create_engine(',
          '    "postgresql://postgres:secret@localhost/mydb",',
          '    pool_size=5,',
          '    max_overflow=10,',
          ')',
          '',
          'with Session(engine) as session:',
          '    users = session.query(User).filter(',
          '        User.active == True',
          '    ).all()',
        ].join('\n'),
      },
    ],
  },
  {
    language: 'java',
    languageLabel: 'Java',
    methods: [
      {
        id: 'raw-driver',
        label: 'JDBC',
        library: 'postgresql-jdbc',
        description: 'Official PostgreSQL JDBC driver for direct database access.',
        steps: [
          'Load JDBC driver',
          'Create connection via DriverManager',
          'Create PreparedStatement',
          'Execute query',
          'Process ResultSet',
          'Close resources (try-with-resources)',
        ],
        codeSnippet: [
          'import java.sql.*;',
          '',
          'String url = "jdbc:postgresql://localhost:5432/mydb";',
          'try (Connection conn = DriverManager.getConnection(',
          '        url, "postgres", "secret");',
          '     PreparedStatement stmt = conn.prepareStatement(',
          '        "SELECT * FROM users WHERE id = ?")) {',
          '    stmt.setInt(1, 1);',
          '    ResultSet rs = stmt.executeQuery();',
          '    while (rs.next()) {',
          '        System.out.println(rs.getString("name"));',
          '    }',
          '}',
        ].join('\n'),
      },
      {
        id: 'pool',
        label: 'HikariCP',
        library: 'hikaricp',
        description: 'High-performance JDBC connection pool used by Spring Boot by default.',
        steps: [
          'Configure HikariConfig (jdbcUrl, username, password)',
          'Set pool properties (maximumPoolSize, minimumIdle)',
          'Create HikariDataSource',
          'Get connection from pool',
          'Execute query',
          'Connection auto-returned on close',
        ],
        codeSnippet: [
          'import com.zaxxer.hikari.*;',
          '',
          'HikariConfig config = new HikariConfig();',
          'config.setJdbcUrl("jdbc:postgresql://localhost:5432/mydb");',
          'config.setUsername("postgres");',
          'config.setPassword("secret");',
          'config.setMaximumPoolSize(10);',
          '',
          'HikariDataSource ds = new HikariDataSource(config);',
          'try (Connection conn = ds.getConnection();',
          '     PreparedStatement ps = conn.prepareStatement(',
          '        "SELECT NOW()")) {',
          '    ResultSet rs = ps.executeQuery();',
          '    rs.next();',
          '    System.out.println(rs.getTimestamp(1));',
          '}',
        ].join('\n'),
      },
    ],
  },
  {
    language: 'cpp',
    languageLabel: 'C++',
    methods: [
      {
        id: 'raw-driver',
        label: 'libpq',
        library: 'libpq',
        description: 'The official C/C++ client library for PostgreSQL, included with PostgreSQL.',
        steps: [
          'Include libpq-fe.h',
          'Create connection string',
          'Connect with PQconnectdb()',
          'Check connection status',
          'Execute query with PQexec()',
          'Process PGresult and free resources',
        ],
        codeSnippet: [
          '#include <libpq-fe.h>',
          '#include <iostream>',
          '',
          'int main() {',
          '    PGconn* conn = PQconnectdb(',
          '        "host=localhost port=5432 "',
          '        "dbname=mydb user=postgres "',
          '        "password=secret"',
          '    );',
          '    if (PQstatus(conn) != CONNECTION_OK) {',
          '        std::cerr << PQerrorMessage(conn);',
          '        PQfinish(conn);',
          '        return 1;',
          '    }',
          '    PGresult* res = PQexec(conn, "SELECT NOW()");',
          '    std::cout << PQgetvalue(res, 0, 0);',
          '    PQclear(res);',
          '    PQfinish(conn);',
          '}',
        ].join('\n'),
      },
      {
        id: 'orm',
        label: 'libpqxx',
        library: 'libpqxx',
        description: 'Modern C++ wrapper around libpq with RAII and type safety.',
        steps: [
          'Include pqxx headers',
          'Create pqxx::connection',
          'Create transaction (pqxx::work)',
          'Execute parameterized query',
          'Iterate result rows',
          'Commit transaction (auto-rollback on exception)',
        ],
        codeSnippet: [
          '#include <pqxx/pqxx>',
          '#include <iostream>',
          '',
          'int main() {',
          '    pqxx::connection conn(',
          '        "host=localhost port=5432 "',
          '        "dbname=mydb user=postgres "',
          '        "password=secret"',
          '    );',
          '    pqxx::work txn(conn);',
          '    auto result = txn.exec(',
          '        "SELECT id, name FROM users"',
          '    );',
          '    for (auto row : result) {',
          '        std::cout << row["id"].as<int>()',
          '                  << ": " << row["name"].c_str()',
          '                  << std::endl;',
          '    }',
          '    txn.commit();',
          '}',
        ].join('\n'),
      },
    ],
  },
];

export const enterpriseUseCases: EnterpriseUseCase[] = [
  {
    company: 'Apple',
    industry: 'Technology',
    useCase: 'iCloud infrastructure and internal analytics platforms',
    scale: '1000+ PostgreSQL instances',
    whyPostgres: 'Reliability, extensibility, and JSONB for semi-structured data',
  },
  {
    company: 'Instagram',
    industry: 'Social Media',
    useCase: 'User data, feeds, and activity storage',
    scale: 'Billions of rows with custom sharding',
    whyPostgres: 'Started on Django + PG, scaled with custom sharding rather than migrating',
  },
  {
    company: 'Spotify',
    industry: 'Music Streaming',
    useCase: 'User accounts, playlists, and social features',
    scale: '500M+ users, thousands of microservices',
    whyPostgres: 'Mature replication, LISTEN/NOTIFY for real-time features',
  },
  {
    company: 'Reddit',
    industry: 'Social Media',
    useCase: 'Comments, votes, subreddit metadata',
    scale: '430M+ monthly active users',
    whyPostgres: 'Full-text search, JSONB flexibility, robust partitioning',
  },
  {
    company: 'Twitch',
    industry: 'Live Streaming',
    useCase: 'Chat metadata, channel state, user subscriptions',
    scale: '140M+ monthly users',
    whyPostgres: 'Low-latency reads, logical replication for analytics',
  },
  {
    company: 'Goldman Sachs',
    industry: 'Finance',
    useCase: 'Trade settlement, risk analytics, compliance reporting',
    scale: 'Mission-critical financial data',
    whyPostgres: 'ACID compliance, row-level security, audit logging',
  },
];

export const practiceExamples: PgExample[] = [
  {
    id: 'select-basics',
    title: 'SELECT Basics',
    difficulty: 'basic',
    description: 'Retrieve all employees from the employees table, sorted by hire date.',
    setupSQL: [
      'CREATE TABLE employees (',
      '  id SERIAL PRIMARY KEY,',
      '  name VARCHAR(100),',
      '  department VARCHAR(50),',
      '  salary NUMERIC(10,2),',
      '  hire_date DATE',
      ');',
      '',
      'INSERT INTO employees VALUES',
      "  (1, 'Alice', 'Engineering', 95000, '2020-01-15'),",
      "  (2, 'Bob', 'Marketing', 72000, '2019-06-01'),",
      "  (3, 'Carol', 'Engineering', 105000, '2018-03-20'),",
      "  (4, 'Dave', 'Sales', 68000, '2021-09-10'),",
      "  (5, 'Eve', 'Engineering', 115000, '2017-11-30');",
    ].join('\n'),
    challenge: 'Write a query to get all employees sorted by hire_date (oldest first).',
    hint: 'Use ORDER BY with the hire_date column. The default sort order is ascending (ASC).',
    solution: 'SELECT * FROM employees ORDER BY hire_date;',
    expectedOutput: [
      { id: 5, name: 'Eve', department: 'Engineering', salary: 115000, hire_date: '2017-11-30' },
      { id: 3, name: 'Carol', department: 'Engineering', salary: 105000, hire_date: '2018-03-20' },
      { id: 2, name: 'Bob', department: 'Marketing', salary: 72000, hire_date: '2019-06-01' },
      { id: 1, name: 'Alice', department: 'Engineering', salary: 95000, hire_date: '2020-01-15' },
      { id: 4, name: 'Dave', department: 'Sales', salary: 68000, hire_date: '2021-09-10' },
    ],
  },
  {
    id: 'where-filter',
    title: 'WHERE Filtering',
    difficulty: 'basic',
    description: 'Filter employees by department and salary threshold.',
    setupSQL: '-- Uses the same employees table from SELECT Basics',
    challenge: 'Find all Engineering employees earning more than $100,000.',
    hint: 'Use WHERE with AND to combine two conditions: department and salary.',
    solution: "SELECT * FROM employees WHERE department = 'Engineering' AND salary > 100000;",
    expectedOutput: [
      { id: 3, name: 'Carol', department: 'Engineering', salary: 105000, hire_date: '2018-03-20' },
      { id: 5, name: 'Eve', department: 'Engineering', salary: 115000, hire_date: '2017-11-30' },
    ],
  },
  {
    id: 'aggregate-group',
    title: 'Aggregation & GROUP BY',
    difficulty: 'basic',
    description: 'Calculate department-level salary statistics.',
    setupSQL: '-- Uses the same employees table from SELECT Basics',
    challenge: 'Get the average salary and employee count for each department.',
    hint: 'Use GROUP BY department with AVG() and COUNT() aggregate functions.',
    solution: 'SELECT department, COUNT(*) AS emp_count, ROUND(AVG(salary), 2) AS avg_salary FROM employees GROUP BY department ORDER BY avg_salary DESC;',
    expectedOutput: [
      { department: 'Engineering', emp_count: 3, avg_salary: 105000 },
      { department: 'Marketing', emp_count: 1, avg_salary: 72000 },
      { department: 'Sales', emp_count: 1, avg_salary: 68000 },
    ],
  },
  {
    id: 'join-basics',
    title: 'JOIN Basics',
    difficulty: 'intermediate',
    description: 'Join employees with their department details.',
    setupSQL: [
      '-- Assumes employees table exists',
      'CREATE TABLE departments (',
      '  id SERIAL PRIMARY KEY,',
      '  name VARCHAR(50) UNIQUE,',
      '  budget NUMERIC(12,2),',
      '  location VARCHAR(100)',
      ');',
      '',
      'INSERT INTO departments VALUES',
      "  (1, 'Engineering', 2000000, 'Building A'),",
      "  (2, 'Marketing', 800000, 'Building B'),",
      "  (3, 'Sales', 600000, 'Building C');",
    ].join('\n'),
    challenge: 'List each employee with their department location and budget. Include employees even if their department is missing.',
    hint: 'Use LEFT JOIN on the department name. LEFT JOIN keeps all rows from the left table (employees) even without a match.',
    solution: [
      'SELECT e.name, e.salary, d.location, d.budget',
      'FROM employees e',
      'LEFT JOIN departments d ON e.department = d.name',
      'ORDER BY e.name;',
    ].join('\n'),
    expectedOutput: [
      { name: 'Alice', salary: 95000, location: 'Building A', budget: 2000000 },
      { name: 'Bob', salary: 72000, location: 'Building B', budget: 800000 },
      { name: 'Carol', salary: 105000, location: 'Building A', budget: 2000000 },
      { name: 'Dave', salary: 68000, location: 'Building C', budget: 600000 },
      { name: 'Eve', salary: 115000, location: 'Building A', budget: 2000000 },
    ],
  },
  {
    id: 'subquery-window',
    title: 'Subquery & Window Functions',
    difficulty: 'intermediate',
    description: 'Rank employees within their department by salary.',
    setupSQL: '-- Uses the same employees table from SELECT Basics',
    challenge: 'For each employee, show their salary rank within their department (highest salary = rank 1).',
    hint: 'Use the RANK() or ROW_NUMBER() window function with PARTITION BY department ORDER BY salary DESC.',
    solution: [
      'SELECT name, department, salary,',
      '  RANK() OVER (PARTITION BY department ORDER BY salary DESC) AS dept_rank',
      'FROM employees',
      'ORDER BY department, dept_rank;',
    ].join('\n'),
    expectedOutput: [
      { name: 'Eve', department: 'Engineering', salary: 115000, dept_rank: 1 },
      { name: 'Carol', department: 'Engineering', salary: 105000, dept_rank: 2 },
      { name: 'Alice', department: 'Engineering', salary: 95000, dept_rank: 3 },
      { name: 'Bob', department: 'Marketing', salary: 72000, dept_rank: 1 },
      { name: 'Dave', department: 'Sales', salary: 68000, dept_rank: 1 },
    ],
  },
  {
    id: 'cte-recursive',
    title: 'Common Table Expressions (CTEs)',
    difficulty: 'intermediate',
    description: 'Use CTEs to break complex queries into readable steps.',
    setupSQL: [
      '-- Uses employees table',
      'CREATE TABLE projects (',
      '  id SERIAL PRIMARY KEY,',
      '  name VARCHAR(100),',
      '  lead_id INT REFERENCES employees(id),',
      '  start_date DATE,',
      '  status VARCHAR(20)',
      ');',
      '',
      'INSERT INTO projects VALUES',
      "  (1, 'Platform Rewrite', 5, '2023-01-10', 'active'),",
      "  (2, 'Mobile App v2', 1, '2023-06-01', 'active'),",
      "  (3, 'Data Pipeline', 3, '2022-11-15', 'completed');",
    ].join('\n'),
    challenge: 'Find active projects where the lead earns above the company average salary. Show project name, lead name, and their salary.',
    hint: 'Use a CTE to first calculate the average salary, then join it with projects and employees.',
    solution: [
      'WITH avg_sal AS (',
      '  SELECT AVG(salary) AS company_avg FROM employees',
      ')',
      'SELECT p.name AS project, e.name AS lead, e.salary',
      'FROM projects p',
      'JOIN employees e ON p.lead_id = e.id',
      'CROSS JOIN avg_sal',
      "WHERE p.status = 'active' AND e.salary > avg_sal.company_avg",
      'ORDER BY e.salary DESC;',
    ].join('\n'),
    expectedOutput: [
      { project: 'Platform Rewrite', lead: 'Eve', salary: 115000 },
      { project: 'Mobile App v2', lead: 'Alice', salary: 95000 },
    ],
  },
  {
    id: 'distinct-values',
    title: 'DISTINCT & Counting',
    difficulty: 'basic',
    description: 'Find unique values and count distinct entries.',
    setupSQL: '-- Uses the same employees table from SELECT Basics',
    challenge: 'List all unique departments and count how many distinct departments exist.',
    hint: 'Use SELECT DISTINCT to get unique values. Use COUNT(DISTINCT column) to count them.',
    solution: 'SELECT DISTINCT department FROM employees ORDER BY department;',
    expectedOutput: [
      { department: 'Engineering' },
      { department: 'Marketing' },
      { department: 'Sales' },
    ],
  },
  {
    id: 'having-clause',
    title: 'HAVING Clause',
    difficulty: 'basic',
    description: 'Filter grouped results using HAVING.',
    setupSQL: '-- Uses the same employees table from SELECT Basics',
    challenge: 'Find departments that have more than 1 employee. Show department name and count.',
    hint: 'Use GROUP BY with HAVING to filter groups. HAVING is like WHERE but for aggregated results.',
    solution: 'SELECT department, COUNT(*) AS emp_count FROM employees GROUP BY department HAVING COUNT(*) > 1;',
    expectedOutput: [
      { department: 'Engineering', emp_count: 3 },
    ],
  },
  {
    id: 'case-expression',
    title: 'CASE Expressions',
    difficulty: 'intermediate',
    description: 'Use conditional logic inside SQL queries.',
    setupSQL: '-- Uses the same employees table from SELECT Basics',
    challenge: 'Classify each employee as "Senior" (salary >= 100000), "Mid" (salary >= 70000), or "Junior" (below 70000). Show name, salary, and the level.',
    hint: 'Use CASE WHEN ... THEN ... ELSE ... END to create conditional categories.',
    solution: [
      'SELECT name, salary,',
      '  CASE',
      '    WHEN salary >= 100000 THEN \'Senior\'',
      '    WHEN salary >= 70000 THEN \'Mid\'',
      '    ELSE \'Junior\'',
      '  END AS level',
      'FROM employees',
      'ORDER BY salary DESC;',
    ].join('\n'),
    expectedOutput: [
      { name: 'Eve', salary: 115000, level: 'Senior' },
      { name: 'Carol', salary: 105000, level: 'Senior' },
      { name: 'Alice', salary: 95000, level: 'Mid' },
      { name: 'Bob', salary: 72000, level: 'Mid' },
      { name: 'Dave', salary: 68000, level: 'Junior' },
    ],
  },
  {
    id: 'string-functions',
    title: 'String Functions',
    difficulty: 'basic',
    description: 'Manipulate text data using built-in string functions.',
    setupSQL: '-- Uses the same employees table from SELECT Basics',
    challenge: 'Show each employee name in uppercase, their department in lowercase, and the length of their name.',
    hint: 'Use UPPER(), LOWER(), and LENGTH() functions.',
    solution: 'SELECT UPPER(name) AS upper_name, LOWER(department) AS lower_dept, LENGTH(name) AS name_length FROM employees ORDER BY name;',
    expectedOutput: [
      { upper_name: 'ALICE', lower_dept: 'engineering', name_length: 5 },
      { upper_name: 'BOB', lower_dept: 'marketing', name_length: 3 },
      { upper_name: 'CAROL', lower_dept: 'engineering', name_length: 5 },
      { upper_name: 'DAVE', lower_dept: 'sales', name_length: 4 },
      { upper_name: 'EVE', lower_dept: 'engineering', name_length: 3 },
    ],
  },
  {
    id: 'date-functions',
    title: 'Date Functions & Intervals',
    difficulty: 'intermediate',
    description: 'Work with dates using PostgreSQL date functions.',
    setupSQL: '-- Uses the same employees table from SELECT Basics',
    challenge: 'Show each employee name, their hire date, and how many years they have been employed (as of 2024-01-01). Round to 1 decimal.',
    hint: 'Use AGE() to get the interval between dates, then EXTRACT(YEAR FROM ...) to get years. Or use date subtraction with division.',
    solution: [
      'SELECT name, hire_date,',
      "  ROUND(EXTRACT(EPOCH FROM AGE('2024-01-01'::date, hire_date)) / 86400 / 365.25, 1) AS years_employed",
      'FROM employees',
      'ORDER BY years_employed DESC;',
    ].join('\n'),
    expectedOutput: [
      { name: 'Eve', hire_date: '2017-11-30', years_employed: 6.1 },
      { name: 'Carol', hire_date: '2018-03-20', years_employed: 5.8 },
      { name: 'Bob', hire_date: '2019-06-01', years_employed: 4.6 },
      { name: 'Alice', hire_date: '2020-01-15', years_employed: 3.9 },
      { name: 'Dave', hire_date: '2021-09-10', years_employed: 2.3 },
    ],
  },
  {
    id: 'self-join',
    title: 'Self JOIN',
    difficulty: 'intermediate',
    description: 'Compare rows within the same table using self-joins.',
    setupSQL: '-- Uses the same employees table from SELECT Basics',
    challenge: 'Find all pairs of employees in the same department. Show both names and the department. Avoid duplicate pairs (Alice-Carol and Carol-Alice).',
    hint: 'JOIN employees with itself on department. Use e1.id < e2.id to avoid duplicates.',
    solution: [
      'SELECT e1.name AS employee_1, e2.name AS employee_2, e1.department',
      'FROM employees e1',
      'JOIN employees e2 ON e1.department = e2.department AND e1.id < e2.id',
      'ORDER BY e1.department, e1.name;',
    ].join('\n'),
    expectedOutput: [
      { employee_1: 'Alice', employee_2: 'Carol', department: 'Engineering' },
      { employee_1: 'Alice', employee_2: 'Eve', department: 'Engineering' },
      { employee_1: 'Carol', employee_2: 'Eve', department: 'Engineering' },
    ],
  },
];

export function getTopicBySlug(slug: string): PostgresTopic | undefined {
  return postgresTopics.find((t) => t.slug === slug);
}

export function getDriversByLanguage(language: string): ConnectionDriver | undefined {
  return connectionDrivers.find((d) => d.language === language);
}

export function getExamplesByDifficulty(difficulty: string): PgExample[] {
  return practiceExamples.filter((e) => e.difficulty === difficulty);
}
