import type { SandboxExercise } from '@/types/sandbox';

export const sqlExercises: SandboxExercise[] = [
  {
    id: 'sql-select-basic',
    title: 'Basic SELECT',
    difficulty: 'beginner',
    language: 'sql',
    category: 'SELECT',
    description: 'Retrieve all columns from the employees table.',
    challenge: 'Write a query to select all employees from the employees table.',
    hint: 'Use SELECT * to retrieve all columns from a table.',
    starterCode: 'SELECT ',
    solution: 'SELECT * FROM employees;',
    alternativeSolutions: ['SELECT * FROM employees'],
    requiredKeywords: ['select', 'from', 'employees'],
    setupContext: 'Table: employees (id, name, department, salary, hire_date)',
    precomputedResults: [
      { id: 1, name: 'Alice', department: 'Engineering', salary: 95000, hire_date: '2022-01-15' },
      { id: 2, name: 'Bob', department: 'Marketing', salary: 72000, hire_date: '2021-06-01' },
      { id: 3, name: 'Carol', department: 'Engineering', salary: 105000, hire_date: '2020-03-10' },
      { id: 4, name: 'Dave', department: 'Sales', salary: 68000, hire_date: '2023-02-20' },
      { id: 5, name: 'Eve', department: 'Engineering', salary: 112000, hire_date: '2019-11-05' },
    ],
  },
  {
    id: 'sql-where-clause',
    title: 'WHERE Clause Filtering',
    difficulty: 'beginner',
    language: 'sql',
    category: 'WHERE',
    description: 'Filter rows using a WHERE clause.',
    challenge: 'Find all employees in the Engineering department.',
    hint: "Use WHERE department = 'Engineering' to filter results.",
    starterCode: "SELECT * FROM employees\nWHERE ",
    solution: "SELECT * FROM employees WHERE department = 'Engineering';",
    alternativeSolutions: [
      "SELECT * FROM employees WHERE department = 'Engineering'",
      'SELECT * FROM employees WHERE department = \'Engineering\'',
    ],
    requiredKeywords: ['select', 'from', 'where', 'engineering'],
    setupContext: 'Table: employees (id, name, department, salary, hire_date)',
    precomputedResults: [
      { id: 1, name: 'Alice', department: 'Engineering', salary: 95000, hire_date: '2022-01-15' },
      { id: 3, name: 'Carol', department: 'Engineering', salary: 105000, hire_date: '2020-03-10' },
      { id: 5, name: 'Eve', department: 'Engineering', salary: 112000, hire_date: '2019-11-05' },
    ],
  },
  {
    id: 'sql-order-by',
    title: 'ORDER BY Sorting',
    difficulty: 'beginner',
    language: 'sql',
    category: 'ORDER BY',
    description: 'Sort query results.',
    challenge: 'List all employees ordered by salary from highest to lowest.',
    hint: 'Use ORDER BY salary DESC to sort in descending order.',
    starterCode: 'SELECT * FROM employees\nORDER BY ',
    solution: 'SELECT * FROM employees ORDER BY salary DESC;',
    alternativeSolutions: ['SELECT * FROM employees ORDER BY salary DESC'],
    requiredKeywords: ['select', 'order by', 'desc'],
    setupContext: 'Table: employees (id, name, department, salary, hire_date)',
    precomputedResults: [
      { id: 5, name: 'Eve', salary: 112000 },
      { id: 3, name: 'Carol', salary: 105000 },
      { id: 1, name: 'Alice', salary: 95000 },
      { id: 2, name: 'Bob', salary: 72000 },
      { id: 4, name: 'Dave', salary: 68000 },
    ],
  },
  {
    id: 'sql-aggregate-count',
    title: 'COUNT with GROUP BY',
    difficulty: 'intermediate',
    language: 'sql',
    category: 'Aggregation',
    description: 'Count employees per department.',
    challenge: 'Count the number of employees in each department.',
    hint: 'Use COUNT(*) with GROUP BY department.',
    starterCode: 'SELECT department, \nFROM employees\n',
    solution: 'SELECT department, COUNT(*) as count FROM employees GROUP BY department;',
    alternativeSolutions: [
      'SELECT department, COUNT(*) FROM employees GROUP BY department',
      'SELECT department, COUNT(*) as employee_count FROM employees GROUP BY department',
      'SELECT department, COUNT(id) as count FROM employees GROUP BY department',
    ],
    requiredKeywords: ['count', 'group by'],
    setupContext: 'Table: employees (id, name, department, salary, hire_date)',
    precomputedResults: [
      { department: 'Engineering', count: 3 },
      { department: 'Marketing', count: 1 },
      { department: 'Sales', count: 1 },
    ],
  },
  {
    id: 'sql-avg-having',
    title: 'AVG with HAVING',
    difficulty: 'intermediate',
    language: 'sql',
    category: 'Aggregation',
    description: 'Filter groups using HAVING.',
    challenge: 'Find departments where the average salary exceeds $80,000.',
    hint: 'Use GROUP BY with HAVING AVG(salary) > 80000.',
    starterCode: 'SELECT department, AVG(salary) as avg_salary\nFROM employees\n',
    solution: 'SELECT department, AVG(salary) as avg_salary FROM employees GROUP BY department HAVING AVG(salary) > 80000;',
    alternativeSolutions: [
      'SELECT department, AVG(salary) avg_salary FROM employees GROUP BY department HAVING AVG(salary) > 80000',
    ],
    requiredKeywords: ['avg', 'group by', 'having'],
    setupContext: 'Table: employees (id, name, department, salary, hire_date)',
    precomputedResults: [
      { department: 'Engineering', avg_salary: 104000 },
    ],
  },
  {
    id: 'sql-inner-join',
    title: 'INNER JOIN',
    difficulty: 'intermediate',
    language: 'sql',
    category: 'JOIN',
    description: 'Join two tables to combine related data.',
    challenge: 'List all employees with their project names using an INNER JOIN.',
    hint: 'JOIN the projects table on employee_id = employees.id.',
    starterCode: 'SELECT e.name, p.project_name\nFROM employees e\n',
    solution: 'SELECT e.name, p.project_name FROM employees e INNER JOIN projects p ON p.employee_id = e.id;',
    alternativeSolutions: [
      'SELECT e.name, p.project_name FROM employees e JOIN projects p ON p.employee_id = e.id',
      'SELECT e.name, p.project_name FROM employees e INNER JOIN projects p ON e.id = p.employee_id',
    ],
    requiredKeywords: ['join', 'on'],
    setupContext: 'Tables: employees (id, name, department, salary), projects (id, project_name, employee_id)',
    precomputedResults: [
      { name: 'Alice', project_name: 'API Gateway' },
      { name: 'Alice', project_name: 'Auth Service' },
      { name: 'Carol', project_name: 'Data Pipeline' },
      { name: 'Eve', project_name: 'ML Platform' },
    ],
  },
  {
    id: 'sql-left-join',
    title: 'LEFT JOIN',
    difficulty: 'intermediate',
    language: 'sql',
    category: 'JOIN',
    description: 'Include unmatched rows from the left table.',
    challenge: 'List ALL employees and their projects (include employees without projects).',
    hint: 'Use LEFT JOIN to include employees even if they have no projects.',
    starterCode: 'SELECT e.name, p.project_name\nFROM employees e\n',
    solution: 'SELECT e.name, p.project_name FROM employees e LEFT JOIN projects p ON p.employee_id = e.id;',
    alternativeSolutions: [
      'SELECT e.name, p.project_name FROM employees e LEFT OUTER JOIN projects p ON p.employee_id = e.id',
    ],
    requiredKeywords: ['left join', 'on'],
    setupContext: 'Tables: employees (id, name, department, salary), projects (id, project_name, employee_id)',
    precomputedResults: [
      { name: 'Alice', project_name: 'API Gateway' },
      { name: 'Alice', project_name: 'Auth Service' },
      { name: 'Bob', project_name: null },
      { name: 'Carol', project_name: 'Data Pipeline' },
      { name: 'Dave', project_name: null },
      { name: 'Eve', project_name: 'ML Platform' },
    ],
  },
  {
    id: 'sql-subquery',
    title: 'Subquery',
    difficulty: 'advanced',
    language: 'sql',
    category: 'Subquery',
    description: 'Use a subquery to filter results.',
    challenge: 'Find employees who earn more than the average salary.',
    hint: 'Use a subquery: WHERE salary > (SELECT AVG(salary) FROM employees).',
    starterCode: 'SELECT name, salary\nFROM employees\nWHERE salary > ',
    solution: 'SELECT name, salary FROM employees WHERE salary > (SELECT AVG(salary) FROM employees);',
    alternativeSolutions: [
      'SELECT name, salary FROM employees WHERE salary > (SELECT AVG(salary) FROM employees)',
    ],
    requiredKeywords: ['select', 'where', 'avg'],
    setupContext: 'Table: employees (id, name, department, salary, hire_date). Average salary is ~90,400.',
    precomputedResults: [
      { name: 'Alice', salary: 95000 },
      { name: 'Carol', salary: 105000 },
      { name: 'Eve', salary: 112000 },
    ],
  },
  {
    id: 'sql-window-rank',
    title: 'Window Function: RANK',
    difficulty: 'advanced',
    language: 'sql',
    category: 'Window Functions',
    description: 'Rank employees within their department by salary.',
    challenge: 'Rank employees by salary within each department using RANK().',
    hint: 'Use RANK() OVER (PARTITION BY department ORDER BY salary DESC).',
    starterCode: 'SELECT name, department, salary,\n  RANK() OVER (\n    \n  ) as salary_rank\nFROM employees;',
    solution: 'SELECT name, department, salary, RANK() OVER (PARTITION BY department ORDER BY salary DESC) as salary_rank FROM employees;',
    alternativeSolutions: [
      'SELECT name, department, salary, RANK() OVER (PARTITION BY department ORDER BY salary DESC) salary_rank FROM employees',
    ],
    requiredKeywords: ['rank', 'over', 'partition by', 'order by'],
    setupContext: 'Table: employees (id, name, department, salary, hire_date)',
    precomputedResults: [
      { name: 'Eve', department: 'Engineering', salary: 112000, salary_rank: 1 },
      { name: 'Carol', department: 'Engineering', salary: 105000, salary_rank: 2 },
      { name: 'Alice', department: 'Engineering', salary: 95000, salary_rank: 3 },
      { name: 'Bob', department: 'Marketing', salary: 72000, salary_rank: 1 },
      { name: 'Dave', department: 'Sales', salary: 68000, salary_rank: 1 },
    ],
  },
  {
    id: 'sql-cte',
    title: 'Common Table Expression (CTE)',
    difficulty: 'advanced',
    language: 'sql',
    category: 'CTE',
    description: 'Use a CTE for cleaner complex queries.',
    challenge: 'Using a CTE, find departments where total salary exceeds $100,000.',
    hint: 'Start with WITH dept_totals AS (...) then SELECT from it.',
    starterCode: 'WITH dept_totals AS (\n  \n)\nSELECT * FROM dept_totals\nWHERE total_salary > 100000;',
    solution: 'WITH dept_totals AS (SELECT department, SUM(salary) as total_salary FROM employees GROUP BY department) SELECT * FROM dept_totals WHERE total_salary > 100000;',
    alternativeSolutions: [
      'WITH dept_totals AS (SELECT department, SUM(salary) total_salary FROM employees GROUP BY department) SELECT * FROM dept_totals WHERE total_salary > 100000',
    ],
    requiredKeywords: ['with', 'as', 'sum', 'group by'],
    setupContext: 'Table: employees (id, name, department, salary, hire_date)',
    precomputedResults: [
      { department: 'Engineering', total_salary: 312000 },
    ],
  },
  {
    id: 'sql-create-index',
    title: 'Create an Index',
    difficulty: 'intermediate',
    language: 'sql',
    category: 'Performance',
    description: 'Create an index for query optimization.',
    challenge: 'Create an index on the employees table for the department column.',
    hint: 'Use CREATE INDEX idx_name ON table(column).',
    starterCode: 'CREATE INDEX ',
    solution: 'CREATE INDEX idx_employees_department ON employees(department);',
    alternativeSolutions: [
      'CREATE INDEX idx_employees_department ON employees (department)',
      'CREATE INDEX idx_dept ON employees(department)',
      'CREATE INDEX idx_department ON employees(department)',
    ],
    requiredKeywords: ['create index', 'on', 'employees', 'department'],
    setupContext: 'Table: employees (id, name, department, salary, hire_date). Queries frequently filter by department.',
    precomputedResults: [{ result: 'CREATE INDEX' }],
  },
  {
    id: 'sql-explain-analyze',
    title: 'EXPLAIN ANALYZE',
    difficulty: 'advanced',
    language: 'sql',
    category: 'Performance',
    description: 'Analyze query execution plans.',
    challenge: 'Write an EXPLAIN ANALYZE for a query that finds high-salary employees.',
    hint: 'Prefix your SELECT with EXPLAIN ANALYZE.',
    starterCode: '',
    solution: 'EXPLAIN ANALYZE SELECT * FROM employees WHERE salary > 100000;',
    alternativeSolutions: [
      'EXPLAIN ANALYZE SELECT * FROM employees WHERE salary > 100000',
      'EXPLAIN ANALYZE SELECT name, salary FROM employees WHERE salary > 100000',
    ],
    requiredKeywords: ['explain analyze', 'select', 'where'],
    setupContext: 'Table: employees (id, name, department, salary, hire_date)',
    precomputedResults: [
      { 'QUERY PLAN': 'Seq Scan on employees (cost=0.00..1.06 rows=3 width=68) (actual time=0.012..0.014 rows=2 loops=1)' },
      { 'QUERY PLAN': '  Filter: (salary > 100000)' },
      { 'QUERY PLAN': '  Rows Removed by Filter: 3' },
      { 'QUERY PLAN': 'Planning Time: 0.045 ms' },
      { 'QUERY PLAN': 'Execution Time: 0.028 ms' },
    ],
  },
];
